# Generated by Django 2.2.7 on 2019-11-09 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Appl_Route',
            fields=[
                ('key_appl_route', models.AutoField(primary_key=True, serialize=False)),
                ('appl_route_text', models.CharField(max_length=200, verbose_name='応募経路')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_Department',
            fields=[
                ('headquarters_text', models.CharField(max_length=100, verbose_name='本部')),
                ('deparment_text', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='部')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='M_Work_History',
            fields=[
                ('key_history_kbn', models.AutoField(primary_key=True, serialize=False)),
                ('work_history_kbn', models.CharField(max_length=100, verbose_name='経歴区分')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='T_Applicant_info',
            fields=[
                ('key_applicant', models.AutoField(primary_key=True, serialize=False)),
                ('applicant_date', models.DateField(verbose_name='応募日')),
                ('key_appl_route', models.IntegerField(null=True)),
                ('applicant_no', models.CharField(max_length=20, verbose_name='応募者No')),
                ('applicant_name_text', models.CharField(max_length=100, verbose_name='応募者名')),
                ('key_history_kbn', models.IntegerField(null=True)),
                ('deparment_1_text', models.CharField(max_length=100, null=True, verbose_name='部')),
                ('judgment_1', models.IntegerField(null=True)),
                ('deparment_2_text', models.CharField(max_length=100, null=True, verbose_name='部')),
                ('judgment_2', models.IntegerField(null=True)),
                ('deparment_3_text', models.CharField(max_length=100, null=True, verbose_name='部')),
                ('judgment_3', models.IntegerField(null=True)),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
