# Generated by Django 2.2.7 on 2019-11-10 13:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0001_initial'),
    ]

