# Generated by Django 2.2.7 on 2019-11-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0002_auto_20191110_2233'),
    ]

    operations = [
        migrations.DeleteModel(
            name='M_Department',
        ),
    ]
