# Generated by Django 2.2.7 on 2019-11-10 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0003_delete_m_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Department',
            fields=[
                ('key_index', models.AutoField(primary_key=True, serialize=False)),
                ('headquarters_text', models.CharField(max_length=100, verbose_name='本部')),
                ('deparment_text', models.CharField(max_length=100, unique=True, verbose_name='部')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
    ]
