# Generated by Django 2.2.7 on 2019-11-16 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0005_auto_20191116_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_applicant_info',
            name='judgment_1',
        ),
        migrations.RemoveField(
            model_name='t_applicant_info',
            name='judgment_2',
        ),
        migrations.RemoveField(
            model_name='t_applicant_info',
            name='judgment_3',
        ),
        migrations.AddField(
            model_name='t_applicant_info',
            name='key_appl_route',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Appl_Route'),
        ),
        migrations.AddField(
            model_name='t_applicant_info',
            name='key_history_kbn',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Work_History', verbose_name='経歴区分'),
        ),
    ]
