# Generated by Django 2.2.7 on 2019-11-16 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0006_auto_20191116_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='T_Judgment',
            fields=[
                ('key_judgment', models.AutoField(primary_key=True, serialize=False)),
                ('judgment_index', models.IntegerField(verbose_name='優先順位')),
                ('u_user', models.CharField(max_length=100, verbose_name='更新者')),
                ('u_date', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('key_applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicantctl.T_Applicant_info')),
                ('key_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Department')),
            ],
        ),
    ]
