# Generated by Django 2.2.7 on 2019-11-17 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0008_remove_m_department_deparment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='t_judgment',
            name='judgment',
            field=models.IntegerField(null=True, verbose_name='判定'),
        ),
        migrations.AlterField(
            model_name='t_judgment',
            name='key_applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicantctl.T_Applicant_info', verbose_name='応募者情報Key'),
        ),
        migrations.AlterField(
            model_name='t_judgment',
            name='key_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Department', verbose_name='本部'),
        ),
    ]
