# Generated by Django 2.2.7 on 2019-11-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0010_auto_20191117_2004'),
    ]


