# Generated by Django 2.2.7 on 2019-11-17 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0011_auto_20191117_2014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='t_judgment',
            name='judgment',
        ),
        migrations.DeleteModel(
            name='M_Judgment',
        ),
    ]
