# Generated by Django 2.2.7 on 2019-11-17 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('applicantctl', '0010_auto_20191117_2004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='m_judgment',
            old_name='department_text',
            new_name='judgment_text',
        ),
        migrations.RenameField(
            model_name='m_judgment',
            old_name='department_value',
            new_name='key_judgment',
        ),
        migrations.AlterField(
            model_name='t_judgment',
            name='judgment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='applicantctl.M_Judgment', to_field='department_value', verbose_name='判定'),
        ),
    ]
